services:
  db:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=quanta
      - POSTGRES_PASSWORD=sekret
      - POSTGRES_DB=quanta
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data:
